### ISSUE TITLE
Ajout d'un fichier de configuration Eslint 

### ISSUE THREAD

**Issue by Arcoz0308** [Melvynx/beginjavascript-module-dom#5]
L'ajout d'un eslint permet au contributeurs du projets d'etre forcé d'utilisé le style de code de l'auteur.

Ce qui reduirais les chances de devoirs repassé par derrière comme dans https://github.com/Melvynx/beginjavascript-module-dom/commit/b5bd80f63f72e2f23a01cc56afd9517b8bdf9a70

**Comment by Melvynx** [comment]
Tu as complété ? Hésites pas à faire une PR.

**Comment by Arcoz0308** [comment]
bah, tu avais rep sur discord il y a un bail.

et je vais pas imposé mon eslint non plus
